# -*- coding: utf-8 -*-
"""DASHBOARD PAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmP41dKZdxsfIfa9QdUbwk1uwCwW7yCT
"""



import streamlit as st
import pandas as pd
import plotly.express as px

# ==========================================================
# CONFIGURACIÓN DE PÁGINA
# ==========================================================

st.set_page_config(
    page_title="SUNAFIL PAS 2026",
    layout="wide"
)

# ==========================================================
# ESTILOS CSS
# ==========================================================

st.markdown("""
<style>

.main {
    background-color: #FFFFFF;
}

/* Título principal */
.titulo-principal{
    text-align:center;
    color:#003B7A;
    font-size:32px;
    font-weight:700;
    margin-bottom:0px;
    padding-bottom:0px;
}

/* Subtítulo */
.subtitulo{
    text-align:center;
    color:#4B5563;
    font-size:18px;
    font-weight:600;
    margin-top:0px;
    margin-bottom:20px;
}

/* Títulos de secciones */
.section-title{
    color:#003B7A;
    font-weight:700;
    font-size:22px;
    margin-top:10px;
    margin-bottom:10px;
}

/* Tarjetas */
[data-testid="stMetric"]{
    background-color:white;
    border:1px solid #D9E2F1;
    border-radius:10px;
    padding:10px;
}

/* Contenedores de gráficos */
[data-testid="stPlotlyChart"]{
    background-color:white;
    border:1px solid #D9E2F1;
    border-radius:10px;
    padding:5px;
}

/* DataFrame */
[data-testid="stDataFrame"] th {
    white-space: normal !important;
    word-wrap: break-word !important;
    text-align: center !important;
    vertical-align: middle !important;
    line-height: 1.1 !important;
}

[data-testid="stDataFrame"] td {
    text-align: center !important;
    vertical-align: middle !important;
}

</style>
""", unsafe_allow_html=True)
# ==========================================================
# CARGA DE DATOS
# ==========================================================

@st.cache_data
def cargar_datos():

    df = pd.read_excel("PAS_2026_JLES.xlsx")

    df.columns = df.columns.str.strip()

    df["DATE"] = pd.to_datetime(
        df["DATE"],
        dayfirst=True,
        errors="coerce"
    )

    # ------------------------
    # INDICADORES
    # ------------------------

    df["EJECUCION MENSUAL"] = (
        df["EJACU"] /
        df["METACU"]
    ).fillna(0)

    df["EJECUCION ANUAL"] = (
        df["EJACU"] /
        df["META ANUAL"]
    ).fillna(0)

    # Evitar infinitos

    df["EJECUCION MENSUAL"] = (
        df["EJECUCION MENSUAL"]
        .replace([float("inf"), -float("inf")], 0)
    )

    df["EJECUCION ANUAL"] = (
        df["EJECUCION ANUAL"]
        .replace([float("inf"), -float("inf")], 0)
    )

    return df

df = cargar_datos()

# ==========================================================
# CATÁLOGO DOCUMENTOS
# ==========================================================

documentos = {
    "IC": "IMPUTACIONES DE CARGO",
    "IFI": "INFORMES FINALES DE INSTRUCCIÓN",
    "IAR": "INFORMES DE ARCHIVAMIENTO",
    "R1ERA": "RESOLUCIONES DE SUBINTENDENCIA",
    "R2DA": "RESOLUCIONES DE INTENDENCIA"
}

df["DOCUMENTO"] = df["COD_DOC"].map(documentos)

# ==========================================================
# FILTROS
# ==========================================================

st.sidebar.header("Filtros")

personales = ["TODOS"] + sorted(
    df["PERSONAL"].dropna().unique()
)

personal = st.sidebar.selectbox(
    "Personal",
    personales
)

meses = (
    df[["MES1", "Mes"]]
    .drop_duplicates()
    .sort_values("MES1")
)

mes = st.sidebar.selectbox(
    "Mes",
    meses["Mes"]
)

mes_seleccionado = meses.loc[
    meses["Mes"] == mes,
    "MES1"
].iloc[0]

intendencias = ["TODAS"] + sorted(
    df["INTENDENCIA"].dropna().unique()
)

intendencia = st.sidebar.selectbox(
    "Intendencia",
    intendencias
)

tipos = ["TODOS"] + sorted(
    df["ESTADO"].dropna().unique()
)

tipo = st.sidebar.selectbox(
    "Estado",
    tipos
)

# ==========================================================
# FILTRO TIPO DOCUMENTO
# ==========================================================

tipos_doc = ["TODOS"] + sorted(df["COD_DOC"].dropna().unique())

tipo_doc = st.sidebar.selectbox(
    "Tipo de Documento",
    tipos_doc
)

# ==========================================================
# FILTROS GLOBALES
# ==========================================================

df_global = df.copy()

if personal != "TODOS":
    df_global = df_global[
        df_global["PERSONAL"] == personal
    ]

if intendencia != "TODAS":
    df_global = df_global[
        df_global["INTENDENCIA"] == intendencia
    ]

if tipo != "TODOS":
    df_global = df_global[
        df_global["ESTADO"] == tipo
    ]

if tipo_doc != "TODOS":
    df_global = df_global[
        df_global["COD_DOC"] == tipo_doc
    ]
# ==========================================================
# CONSOLIDADO NACIONAL
# ==========================================================

if intendencia == "TODAS":

    df_global = (
        df_global
        .groupby(
            ["MES1", "Mes", "COD_DOC"],
            as_index=False
        )
        .agg({
            "META ANUAL": "sum",
            "METACU": "sum",
            "EJACU": "sum",
            "METIN": "sum",
            "EJIN": "sum"
        })
    )

    df_global["EJECUCION MENSUAL"] = (
        df_global["EJACU"] /
        df_global["METACU"]
    ).fillna(0)

    df_global["EJECUCION ANUAL"] = (
        df_global["EJACU"] /
        df_global["META ANUAL"]
    ).fillna(0)

    df_global["INTENDENCIA"] = "NACIONAL"

    df_global["IRE"] = "NACIONAL"

# ==========================================================
# FILTRO MES SOLO TABLA
# ==========================================================

df_tabla = df_global.copy()

df_tabla = df_tabla[
    df_tabla["Mes"] == mes
]

# ==========================================================
# TÍTULOS
# ==========================================================

st.markdown("""
<div class='titulo-principal'>
SUNAFIL: AVANCE DE LAS METAS DEL PROCEDIMIENTO
ADMINISTRATIVO SANCIONADOR 2026 - PERSONAL CAS
</div>
""", unsafe_allow_html=True)

if intendencia == "TODAS":
    subtitulo = "TODAS LAS INTENDENCIAS"
else:
    subtitulo = intendencia

st.markdown(
    f"""
    <div class='subtitulo'>
    {subtitulo}
    </div>
    """,
    unsafe_allow_html=True
)

# ==========================================================
# TABLA RESUMEN / VISTA DINÁMICA
# ==========================================================

if tipo_doc == "TODOS":

    st.markdown(
        "<div class='section-title'>DETALLE METAS PAS 2026</div>",
        unsafe_allow_html=True
    )

    columnas_documentos = [
        "IC",
        "IFI",
        "IAR",
        "R1ERA",
        "R2DA"
    ]

    tabla = pd.DataFrame(
        index=[
            "META ANUAL",
            "META MENSUAL",
            "EJECUCIÓN"
        ]
    )

    for doc in columnas_documentos:

        temp = df_tabla[
            df_tabla["COD_DOC"] == doc
        ]

        if len(temp) > 0:

            fila = temp.iloc[0]

            meta_anual = (
                f"{int(fila['META ANUAL'])} "
                f"({fila['EJECUCION ANUAL']*100:.2f}%)"
            )

            meta_mensual = (
                f"{int(fila['METACU'])} "
                f"({fila['EJECUCION MENSUAL']*100:.2f}%)"
            )

            tabla[documentos[doc]] = [
                meta_anual,
                meta_mensual,
                int(fila["EJACU"])
            ]

        else:

            tabla[documentos[doc]] = [
                "0 (0.00%)",
                "0 (0.00%)",
                0
            ]

    st.dataframe(
        tabla,
        use_container_width=True
    )

else:

    st.markdown(
        f"<div class='section-title'>{documentos[tipo_doc]}</div>",
        unsafe_allow_html=True
    )

    # 🔥 FIX IMPORTANTE: filtrar por documento
    temp_doc = df_tabla[df_tabla["COD_DOC"] == tipo_doc]

    fila = temp_doc.iloc[0] if len(temp_doc) > 0 else None

    if fila is not None:

        col1, col2 = st.columns(2)

        with col1:
            st.metric(
                "EJECUCIÓN MENSUAL",
                f"{fila['EJECUCION MENSUAL']*100:.2f}%"
            )

        with col2:
            st.metric(
                "EJECUCIÓN ANUAL",
                f"{fila['EJECUCION ANUAL']*100:.2f}%"
            )
# ==========================================================
# FUNCIÓN DE GRÁFICOS
# ==========================================================

def crear_grafico(codigo_doc, titulo, mostrar_leyenda=False):

    datos = df_global[
        df_global["COD_DOC"] == codigo_doc
    ].copy()

    # Mostrar desde enero hasta el mes seleccionado
    datos = datos[
        datos["MES1"] <= mes_seleccionado
    ]

    datos = datos.sort_values("MES1")

    fig = px.line()

    fig.add_scatter(
        x=datos["Mes"],
        y=datos["EJECUCION MENSUAL"] * 100,
        mode="lines+markers",
        name="Ejecución Mensual",
        line=dict(color="purple", width=3)
    )

    fig.add_scatter(
        x=datos["Mes"],
        y=datos["EJECUCION ANUAL"] * 100,
        mode="lines+markers",
        name="Ejecución Anual",
        line=dict(color="orange", width=3)
    )
    
    fig.update_layout(
        title=f"{titulo} - Acumulado",
        height=230,
        yaxis_title="Porcentaje (%)",
        xaxis_title="",
        
        showlegend=mostrar_leyenda,
        
        legend=dict(
            orientation="h",
            yanchor="top",
            y=-0.35,
            xanchor="center",
            x=0.5
        ),
        
        margin=dict(
            t=50,
            b=80
        )
    )

    return fig
# ==========================================================
# EN EVALUACIÓN - GRÁFICO NOMINAL INDIVIDUAL
# ==========================================================

def crear_grafico_individual(codigo_doc, titulo, mostrar_leyenda=False):

    datos = df_global[
        df_global["COD_DOC"] == codigo_doc
    ].copy()

    datos = datos[
        datos["MES1"] <= mes_seleccionado
    ]

    datos = datos.sort_values("MES1")

    fig = px.line()

    # Meta Individual
    fig.add_scatter(
        x=datos["Mes"],
        y=datos["METIN"],
        mode="lines+markers",
        name="Meta Individual",
        line=dict(color="green", width=3)
    )

    # Ejecutado Individual
    fig.add_scatter(
        x=datos["Mes"],
        y=datos["EJIN"],
        mode="lines+markers",
        name="Ejecutado Individual",
        line=dict(color="blue", width=3)
    )

    fig.update_layout(
        title=f"{titulo} - Individual",
        height=180,
        showlegend=mostrar_leyenda,
        margin=dict(
            t=40,
            b=20
        ),
        xaxis_title="",
        yaxis_title=""
    )

    return fig

# ==========================================================
# TABLA RANKING INTENDENCIAS (RANKING GLOBAL FIJO)
# ==========================================================

if tipo_doc != "TODOS":

    mes_texto = mes

    # 1. BASE
    df_rank = df.copy()

    # 2. FILTROS (EXCEPTO INTENDENCIA PARA QUE NO ROMPA RANKING)
    if personal != "TODOS":
        df_rank = df_rank[df_rank["PERSONAL"] == personal]

    if tipo != "TODOS":
        df_rank = df_rank[df_rank["ESTADO"] == tipo]

    df_rank = df_rank[
        (df_rank["Mes"] == mes) &
        (df_rank["COD_DOC"] == tipo_doc)
    ]

    # 3. RANKING GLOBAL (FIJO)
    df_rank = df_rank.sort_values(
        by="EJECUCION MENSUAL",
        ascending=False
    ).reset_index(drop=True)

    df_rank["Ranking"] = range(1, len(df_rank) + 1)

    # 4. FILTRO VISUAL (INTENDENCIA NO AFECTA RANKING)
    if intendencia != "TODAS":
        ranking = df_rank[df_rank["INTENDENCIA"] == intendencia].copy()
    else:
        ranking = df_rank.copy()

    # 5. REORDENAR COLUMNAS
    ranking = ranking[
        [
            "Ranking",
            "INTENDENCIA",
            "META ANUAL",
            "METACU",
            "EJACU",
            "EJECUCION MENSUAL",
            "EJECUCION ANUAL"
        ]
    ]

    # 6. RENOMBRES
    ranking.columns = [
        "Ranking",
        "INTENDENCIA",
        "Programado\n2026",
        f"Programado\n{mes_texto}",
        f"Ejecutado\n{mes_texto}",
        f"% ejecución\n{mes_texto}",
        "% ejecución\nAnual"
    ]

# ==========================================================
# GRAFICOS / VISTA DINÁMICA
# ==========================================================

if tipo_doc == "TODOS":

    col1, col2, col3 = st.columns(3)

    with col1:
        st.plotly_chart(
            crear_grafico("IC", "Imputación de Cargos",
            mostrar_leyenda=True),
            use_container_width=True
        )

    with col2:
        st.plotly_chart(
            crear_grafico("IFI", "Informe Final de Instrucción",
            mostrar_leyenda=False),
            use_container_width=True
        )

    with col3:
        st.plotly_chart(
            crear_grafico("IAR", "Informe de Archivamiento",
            mostrar_leyenda=False),
            use_container_width=True
        )

    col4, col5 = st.columns(2)

    with col4:
        st.plotly_chart(
            crear_grafico("R1ERA", "Resolución de Subintendencia",
            mostrar_leyenda=False),
            use_container_width=True
        )

    with col5:
        st.plotly_chart(
            crear_grafico("R2DA", "Resolución de Intendencia",
            mostrar_leyenda=False),
            use_container_width=True
        )

    # ======================================================
    # GRÁFICOS INDIVIDUALES
    # ======================================================

    col1, col2, col3 = st.columns(3)

    with col1:
        st.plotly_chart(
            crear_grafico_individual("IC", "IC"),
            use_container_width=True
        )

    with col2:
        st.plotly_chart(
            crear_grafico_individual("IFI", "IFI"),
            use_container_width=True
        )

    with col3:
        st.plotly_chart(
            crear_grafico_individual("IAR", "IAR"),
            use_container_width=True
        )

    col4, col5 = st.columns(2)

    with col4:
        st.plotly_chart(
            crear_grafico_individual("R1ERA", "R1ERA"),
            use_container_width=True
        )

    with col5:
        st.plotly_chart(
            crear_grafico_individual("R2DA", "R2DA"),
            use_container_width=True
        )

else:

    col_izq, col_der = st.columns([0.8, 1.8])

    # ======================================================
    # GRÁFICOS
    # ======================================================

    with col_izq:

        st.plotly_chart(
            crear_grafico(
                tipo_doc,
                documentos[tipo_doc],
                mostrar_leyenda=True
            ),
            use_container_width=True
        )

        st.plotly_chart(
            crear_grafico_individual(
                tipo_doc,
                tipo_doc
            ),
            use_container_width=True
        )

    # ======================================================
    # RANKING DE INTENDENCIAS
    # ======================================================

    with col_der:

        st.markdown("### Ranking de Intendencias")
        col_heat = "% ejecución\n{mes_texto}" 
        
        
        ranking_style = (
            ranking.style
            .background_gradient(
                cmap="RdYlGn",
                subset=[f"% ejecución\n{mes_texto}"], 
                vmin=0,
                vmax=1
            )
            .format({
                f"% ejecución\n{mes_texto}": "{:.2%}",
                "% ejecución\nAnual": "{:.2%}"
            })
            .set_properties(**{
                "text-align": "center"
            })
        )

        st.dataframe(
            ranking_style,
            use_container_width=True,
            hide_index=True,
            height=520
        )

