# -*- coding: utf-8 -*-
"""DASHBOARD PAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmP41dKZdxsfIfa9QdUbwk1uwCwW7yCT
"""



import streamlit as st
import pandas as pd
import plotly.express as px

# ==========================================================
# CONFIGURACIÓN DE PÁGINA
# ==========================================================

st.set_page_config(
    page_title="SUNAFIL PAS 2026",
    layout="wide"
)

# ==========================================================
# ESTILOS CSS
# ==========================================================

st.markdown("""
<style>

.main {
    background-color: #FFFFFF;
}

/* Título principal */
.titulo-principal{
    text-align:center;
    color:#003B7A;
    font-size:32px;
    font-weight:700;
    margin-bottom:0px;
    padding-bottom:0px;
}

/* Subtítulo */
.subtitulo{
    text-align:center;
    color:#4B5563;
    font-size:18px;
    font-weight:600;
    margin-top:0px;
    margin-bottom:20px;
}

/* Títulos de secciones */
.section-title{
    color:#003B7A;
    font-weight:700;
    font-size:22px;
    margin-top:10px;
    margin-bottom:10px;
}

/* Tarjetas */
[data-testid="stMetric"]{
    background-color:white;
    border:1px solid #D9E2F1;
    border-radius:10px;
    padding:10px;
}

/* Contenedores de gráficos */
[data-testid="stPlotlyChart"]{
    background-color:white;
    border:1px solid #D9E2F1;
    border-radius:10px;
    padding:5px;
}

</style>
""", unsafe_allow_html=True)
# ==========================================================
# CARGA DE DATOS
# ==========================================================

@st.cache_data
def cargar_datos():

    df = pd.read_excel("PAS_2026_JLES.xlsx")

    df.columns = df.columns.str.strip()

    df["DATE"] = pd.to_datetime(
        df["DATE"],
        dayfirst=True,
        errors="coerce"
    )

    # ------------------------
    # INDICADORES
    # ------------------------

    df["EJECUCION MENSUAL"] = (
        df["EJACU"] /
        df["METACU"]
    ).fillna(0)

    df["EJECUCION ANUAL"] = (
        df["EJACU"] /
        df["META ANUAL"]
    ).fillna(0)

    # Evitar infinitos

    df["EJECUCION MENSUAL"] = (
        df["EJECUCION MENSUAL"]
        .replace([float("inf"), -float("inf")], 0)
    )

    df["EJECUCION ANUAL"] = (
        df["EJECUCION ANUAL"]
        .replace([float("inf"), -float("inf")], 0)
    )

    return df

df = cargar_datos()

# ==========================================================
# CATÁLOGO DOCUMENTOS
# ==========================================================

documentos = {
    "IC": "Imputación de Cargos",
    "IFI": "Informe Final de Instrucción",
    "IAR": "Informe de Archivamiento",
    "R1ERA": "Resolución de Subintendencia",
    "R2DA": "Resolución de Intendencia"
}

df["DOCUMENTO"] = df["COD_DOC"].map(documentos)

# ==========================================================
# FILTROS
# ==========================================================

st.sidebar.header("Filtros")

personales = ["TODOS"] + sorted(
    df["PERSONAL"].dropna().unique()
)

personal = st.sidebar.selectbox(
    "Personal",
    personales
)

meses = (
    df[["MES1", "Mes"]]
    .drop_duplicates()
    .sort_values("MES1")
)

mes = st.sidebar.selectbox(
    "Mes",
    meses["Mes"]
)

mes_seleccionado = meses.loc[
    meses["Mes"] == mes,
    "MES1"
].iloc[0]

intendencias = ["TODAS"] + sorted(
    df["INTENDENCIA"].dropna().unique()
)

intendencia = st.sidebar.selectbox(
    "Intendencia",
    intendencias
)

tipos = ["TODOS"] + sorted(
    df["ESTADO"].dropna().unique()
)

tipo = st.sidebar.selectbox(
    "Tipo",
    tipos
)

# ==========================================================
# FILTROS GLOBALES
# ==========================================================

df_global = df.copy()

if personal != "TODOS":
    df_global = df_global[
        df_global["PERSONAL"] == personal
    ]

if intendencia != "TODAS":
    df_global = df_global[
        df_global["INTENDENCIA"] == intendencia
    ]

if tipo != "TODOS":
    df_global = df_global[
        df_global["ESTADO"] == tipo
    ]

# ==========================================================
# FILTRO MES SOLO TABLA
# ==========================================================

df_tabla = df_global.copy()

df_tabla = df_tabla[
    df_tabla["Mes"] == mes
]

# ==========================================================
# TÍTULOS
# ==========================================================

st.markdown("""
<div class='titulo-principal'>
SUNAFIL: AVANCE DE LAS METAS DEL PROCEDIMIENTO
ADMINISTRATIVO SANCIONADOR 2026 - PERSONAL CAS
</div>
""", unsafe_allow_html=True)

if intendencia == "TODAS":
    subtitulo = "TODAS LAS INTENDENCIAS"
else:
    subtitulo = intendencia

st.markdown(
    f"""
    <div class='subtitulo'>
    {subtitulo}
    </div>
    """,
    unsafe_allow_html=True
)

# ==========================================================
# TABLA RESUMEN
# ==========================================================

st.markdown(
    "<div class='section-title'>DETALLE METAS PAS 2026</div>",
    unsafe_allow_html=True
)

columnas_documentos = [
    "IC",
    "IFI",
    "IAR",
    "R1ERA",
    "R2DA"
]

tabla = pd.DataFrame(
    index=[
        "META ANUAL",
        "META MENSUAL",
        "EJECUCIÓN"
    ]
)

for doc in columnas_documentos:

    temp = df_tabla[
        df_tabla["COD_DOC"] == doc
    ]

    if len(temp) > 0:

        fila = temp.iloc[0]

        meta_anual = (
            f"{int(fila['META ANUAL'])} "
            f"🔵({fila['EJECUCION ANUAL']*100:.2f}%)"
        )

        meta_mensual = (
            f"{int(fila['METACU'])} "
            f"🔵({fila['EJECUCION MENSUAL']*100:.2f}%)"
        )

        tabla[documentos[doc]] = [
            meta_anual,
            meta_mensual,
            int(fila["EJACU"])
        ]

    else:

        tabla[documentos[doc]] = [
            "0 (0.00%)",
            "0 (0.00%)",
            0
        ]


st.dataframe(
    tabla,
    use_container_width=True
)

# ==========================================================
# FUNCIÓN DE GRÁFICOS
# ==========================================================

def crear_grafico(codigo_doc, titulo, mostrar_leyenda=False):

    datos = df_global[
        df_global["COD_DOC"] == codigo_doc
    ].copy()

    # Mostrar desde enero hasta el mes seleccionado
    datos = datos[
        datos["MES1"] <= mes_seleccionado
    ]

    datos = datos.sort_values("MES1")

    fig = px.line()

    fig.add_scatter(
        x=datos["Mes"],
        y=datos["EJECUCION MENSUAL"] * 100,
        mode="lines+markers",
        name="Ejecución Mensual",
        line=dict(color="purple", width=3)
    )

    fig.add_scatter(
        x=datos["Mes"],
        y=datos["EJECUCION ANUAL"] * 100,
        mode="lines+markers",
        name="Ejecución Anual",
        line=dict(color="orange", width=3)
    )
    
    fig.update_layout(
        title=titulo,
        height=230,
        yaxis_title="Porcentaje (%)",
        xaxis_title="",
        
        showlegend=mostrar_leyenda,
        
        legend=dict(
            orientation="h",
            yanchor="top",
            y=-0.35,
            xanchor="center",
            x=0.5
        ),
        
        margin=dict(
            t=50,
            b=80
        )
    )

    return fig

# ==========================================================
# GRAFICOS
# ==========================================================

col1, col2, col3 = st.columns(3)

with col1:
    st.plotly_chart(
        crear_grafico("IC", "Imputación de Cargos",
        mostrar_leyenda=True),
        use_container_width=True
    )

with col2:
    st.plotly_chart(
        crear_grafico("IFI", "Informe Final de Instrucción",
        mostrar_leyenda=False),
        use_container_width=True
    )

with col3:
    st.plotly_chart(
        crear_grafico("IAR", "Informe de Archivamiento",
        mostrar_leyenda=False),
        use_container_width=True
    )

col4, col5 = st.columns(2)

with col4:
    st.plotly_chart(
        crear_grafico("R1ERA", "Resolución de Subintendencia",
        mostrar_leyenda=False),
        use_container_width=True
    )

with col5:
    st.plotly_chart(
        crear_grafico("R2DA", "Resolución de Intendencia",
        mostrar_leyenda=False),
        use_container_width=True
    )  
   
